# Generated by Django 5.0.3 on 2024-03-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_box_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='timestampmixin',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
