# Generated by Django 5.0.3 on 2024-03-22 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0003_alter_box_price_alter_timestampmixin_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='sold',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stock.timestampmixin')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.box', verbose_name='التصنيف')),
            ],
            bases=('stock.timestampmixin', models.Model),
        ),
    ]
